version: '3.1'
services:
  fluentd:
    build:
      context: ./fluentd
    image: umbc/idp-fluentd:latest
    logging:
      driver: json-file
      options:
        max-file: "30"
        max-size: "30m"
    ports:
      - 24224:24224/tcp
    restart: always
    volumes:
      - temp-logs-vol:/fluentd/log

  universalforwarder:
    build:
      context: ./universalforwarder
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_DEFAULT_HOSTNAME: ${SPLUNK_DEFAULT_HOSTNAME}
      SPLUNK_PASS4SYMMKEY: ${SPLUNK_PASS4SYMMKEY}
      SPLUNK_SERVER: ${SPLUNK_SERVER}
    image: umbc/idp-universalforwarder:latest
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp
      - temp-logs-vol:/var/log/fluentd-test:ro

volumes:
  logs-vol:
  temp-logs-vol:
