version: '3.1'
services:
  fluentd:
    build:
      context: ./fluentd
    image: ghcr.io/umbc-eis/idp-logger-fluentd:latest
    logging:
      driver: json-file
      options:
        max-file: "30"
        max-size: "30m"
    ports:
      - 24224:24224/tcp
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp

  universalforwarder:
    build:
      context: ./universalforwarder
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_DEFAULT_HOSTNAME: ${SPLUNK_DEFAULT_HOSTNAME}
      SPLUNK_PASS4SYMMKEY: ${SPLUNK_PASS4SYMMKEY}
      SPLUNK_SERVER: ${SPLUNK_SERVER}
    image: ghcr.io/umbc-eis/idp-logger-splunk-uf:latest
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp:ro

  cron:
    build:
      context: ./cron
    image: ghcr.io/umbc-eis/idp-logger-cron:latest
    logging:
      driver: json-file
      options:
        max-file: "30"
        max-size: "30m"
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp

volumes:
  logs-vol:
