version: '3.1'
services:
  syslog:
    build:
      context: ./syslog
    image: umbc/idp-logger:latest
    logging:
      driver: json-file
      options:
        max-file: "30"
        max-size: "30m"
    ports:
      - 5140:514/udp
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp

  universalforwarder:
    build:
      context: ./universalforwarder
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_DEFAULT_HOSTNAME: ${SPLUNK_DEFAULT_HOSTNAME}
      SPLUNK_PASS4SYMMKEY: ${SPLUNK_PASS4SYMMKEY}
      SPLUNK_SERVER: ${SPLUNK_SERVER}
    image: umbc/idp-universalforwarder:latest
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp

  logrotate:
    build:
      context: ./logrotate
    environment:
      - ALL_LOGS_DIRECTORIES=/var/log/umbc-idp
      - LOGROTATE_INTERVAL=daily
    image: umbc/idp-logrotate:latest
    restart: always
    volumes:
      - logs-vol:/var/log/umbc-idp

volumes:
  logs-vol:
