version: '3.1'
services:
  syslog:
    build:
      context: ./syslog
    image: umbc/idp-logger:latest
    ports:
      - 5140:514/udp
    restart: always

  universalforwarder:
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    image: splunk/universalforwarder:latest
